# Generated by Django 6.1 on 2026-08-15 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('headshot_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('circuit', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_position', models.IntegerField()),
                ('win_probability', models.FloatField(blank=True, null=True)),
                ('podium_probability', models.FloatField(blank=True, null=True)),
                ('predicted_points', models.FloatField(blank=True, null=True)),
                ('actual_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='polls.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='polls.race')),
            ],
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('duration', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.race')),
            ],
        ),
        migrations.CreateModel(
            name='LapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.FloatField(blank=True, null=True)),
                ('sector1_time', models.FloatField(blank=True, null=True)),
                ('sector2_time', models.FloatField(blank=True, null=True)),
                ('sector3_time', models.FloatField(blank=True, null=True)),
                ('compound', models.CharField(blank=True, max_length=30)),
                ('tyre_life', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.race')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('fastest_lap', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.season'),
        ),
    ]
